[vms:children]
vagrant
[vagrant]
{{ hostname }}
[vms:vars]
ansible_connection=ssh
ansible_user=vagrant
[targets]
{{ hostname }} ansible_ssh_private_key_file=.vagrant/machines/{{ hostname }}/vsphere/private_key
